# Generated by Django 4.1.4 on 2023-02-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('name', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('icno', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('work', models.TextField(max_length=100)),
            ],
        ),
    ]
